### ISSUE TITLE
Can i konw how you  preprocessed Materport3D dataset

### ISSUE THREAD

**Issue by JackeyPu** [krantiparida/beyond-image-to-depth#11]
first Thank you your excellent work，About Matterport3D ,can you share with me  the procedure to obtain the frames and echoes . It troubled me a lot

**Comment by krantiparida** [comment]
I do not have access to the code currently. I can share the raw image frames with you if you forward the access request acceptance from the authors of the matterport3D dataset.

**Comment by JackeyPu** [comment]
Yesterday, I have sent a mail to Google Groups.Today, They reply a mail to me and give me a access . Can you share the raw images with me? I have run the Replica dataset , the result is same with yours . This is the first work when I am as a postgraduate .I really want to finish the Matterport3D dataset. If you can share the raw images with me ,can you  send a mail to 6720210575@mail.jxust.edu.cn？Please
Very thankful.
![image](https://user-images.githubusercontent.com/110317877/205198243-ba65b20f-05f1-4f71-a14d-d2eac806b11a.png)

**Comment by henu77** [comment]
Thank you very much for your excellent work. 

Google Groups reply a mail to me and give me a access for Matterport3D.

Can you share with me the RGB images and Depth Images about Replica and Matterport3D. But, I only find the echos data in this [link ](https://drive.google.com/drive/folders/1wgioF6FROoK9VLh6gLdvKfUzUrSGG7e8?usp=sharing) .

This is my first project as a postgraduate student. I really want to finish the Replica and Matterport3D dataset. If you can share the RGB images and Depth Images with me ,can you send a mail to [malong@gs.zzu.edu.cn](mailto:malong@gs.zzu.edu.cn) or [77malong@gmail.com](77malong@gmail.com)？

Your assistance is greatly appreciated.

<img width="1036" alt="1ea597119bb530d9a5c6ab6c42a3d8a" src="https://github.com/krantiparida/beyond-image-to-depth/assets/73346969/7627c355-b224-49d6-beb6-c1d3e303df71">
