### ISSUE TITLE
Can i konw how you preprocessed Materport3D dataset

### ISSUE THREAD

**Issue by henu77** [krantiparida/beyond-image-to-depth#12]
Thank you very much for your excellent work. 

Google Groups reply a mail to me and give me a access for Matterport3D.

Can you share with me the RGB images and Depth Images about Replica and Matterport3D. But, I only find the echos data in this [link ](https://drive.google.com/drive/folders/1wgioF6FROoK9VLh6gLdvKfUzUrSGG7e8?usp=sharing) .

This is my first project as a postgraduate student. I really want to finish the Replica and Matterport3D dataset. If you can share the RGB images and Depth Images with me ,can you send a mail to [malong@gs.zzu.edu.cn](mailto:malong@gs.zzu.edu.cn) or [77malong@gmail.com](77malong@gmail.com)？

Your assistance is greatly appreciated.

<img width="1036" alt="1ea597119bb530d9a5c6ab6c42a3d8a" src="https://github.com/krantiparida/beyond-image-to-depth/assets/73346969/7627c355-b224-49d6-beb6-c1d3e303df71">

**Comment by krantiparida** [comment]
shared.
