### ISSUE TITLE
on the partition problem of dataset mp3d

### ISSUE THREAD

**Issue by yyf17** [krantiparida/beyond-image-to-depth#2]
Thank you for your excellent work and hard work.
I have a question as follows:
How do you divide the mp3d data set? I saw in your code that the division of the data set is placed in 3 files (see the code below), but I can't find these 3 files in the code. Can you provide it? Thanks a lot.

“options/base_options.py”
```
			train_scenes_file = os.path.join(self.opt.metadatapath, 'mp3d_scenes_train.txt')
			val_scenes_file = os.path.join(self.opt.metadatapath, 'mp3d_scenes_val.txt')
			test_scenes_file = os.path.join(self.opt.metadatapath, 'mp3d_scenes_test.txt')
```

**Comment by krantiparida** [comment]
I missed it somehow. The files are now added to the dataset folder.

**Comment by yyf17** [comment]
thx
