### ISSUE TITLE
3ms and 5ms sweep sound sources for mp3d

### ISSUE THREAD

**Issue by yyf17** [krantiparida/beyond-image-to-depth#3]
Thank you for your patient help and guidance.
The 3 ms and 5 ms sound source signals with a sampling frequency of 44100 can be obtained from the Git project VisualEchoes (https://github.com/facebookresearch/VisualEchoes).How did you get the signal of the 3 ms and 5 ms sound sources with a sampling frequency of 16000?  

![image](https://user-images.githubusercontent.com/34536352/115019811-44e10480-9eec-11eb-9e5e-80367fbcff63.png)

Thanks a lot.

**Comment by krantiparida** [comment]
I resampled the same signal to 16khz and used it. I have added that now to dataset/source_audio folder. You can directly use that. Thanks.

**Comment by yyf17** [comment]
@krantiparida Thank you very much.
