### ISSUE TITLE
The code of modal fusion 

### ISSUE THREAD

**Issue by helloful** [krantiparida/beyond-image-to-depth#6]
I am very sorry to disturb you. I did not find your modal fusion part  in the code, but there is modal fusion in the paper. Is your code completely public?

**Comment by krantiparida** [comment]
Yes. The modality fusion is implemented [here](https://github.com/krantiparida/beyond-image-to-depth/blob/dcdef5122fa456a92bd58ead4eea0a777158c535/models/networks.py#L125). It is named as `attentionNet` available in `networks.py` inside `models` folder.

**Comment by helloful** [comment]
> Yes. The modality fusion is implemented [here](https://github.com/krantiparida/beyond-image-to-depth/blob/dcdef5122fa456a92bd58ead4eea0a777158c535/models/networks.py#L125). It is named as `attentionNet` available in `networks.py` inside `models` folder.

Thank you very much for your reply

**Comment by helloful** [comment]
> Yes. The modality fusion is implemented [here](https://github.com/krantiparida/beyond-image-to-depth/blob/dcdef5122fa456a92bd58ead4eea0a777158c535/models/networks.py#L125). It is named as `attentionNet` available in `networks.py` inside `models` folder.

Thank you
